sonar.projectKey=smarttask
sonar.projectName=Smarttask
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000
sonar.login=sqp_b73b1dc6eb22d59c3aff5536a9b4a68a9175fabe

# Sources
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.js

# Tests
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.js

# Coverage
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=frontend/tsconfig.json

# Quality thresholds
sonar.qualitygate.wait=true
